# These are supported funding model platforms

# github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_COLLECTIVE
# ko_fi: YOUR_KOFI_USERNAME
# tidelift: npm/PACKAGE_NAME
# community_bridge: PROJECT_NAME
# liberapay: YOUR_LIBERAPAY_USERNAME
# issuehunt: YOUR_ISSUEHUNT_USERNAME
# otechie: YOUR_OTECHIE_USERNAME
# lfx_crowdfunding: PROJECT_NAME
# custom: ['https://paypal.me/YOUR_PAYPAL', 'https://www.buymeacoffee.com/YOUR_USERNAME']

# Uncomment and fill in the relevant lines above if you want to enable sponsorship

